name = "mailfree-api-test"
# name = "mail-exhibit"
main = "src/server.js"
compatibility_date = "2024-01-01"

# 保留 Cloudflare Dashboard 里手动配置的环境变量
keep_vars = true

# D1 数据库绑定
[[d1_databases]]
binding = "TEMP_MAIL_DB"
database_name = "maill_free_db"
database_id = "f8d72ea8-7696-4983-93b3-4b8a7fa8a5dd"

# 静态资源目录
[assets]
directory = "public"
binding = "ASSETS"

# R2 存储桶绑定
[[r2_buckets]]
binding = "MAIL_EML"
bucket_name = "mail-eml"

# 可选：日志服务
# [observability.logs]
# enabled = true
